### ISSUE TITLE
can't generate qr code for some urls

### ISSUE THREAD

**Issue by rdaci23** [paramount-engineering/QR-Code-generator-brightscript#1]
I'm trying to generate a qr code for this url, like this 
 m.qrCode.text = "https://api.auth.adobe.com/api/v1/authenticate?reg_code=YD655RS&requestor_id=myId &mso_id=DTV&no_iframe=false but it throws  Assertion error

**Comment by yungblood** [comment]
Looking into it.

**Comment by yungblood** [comment]
Found minor flaw in slice function. Fixed, and confirmed that existing demo QR codes still work along with the one mentioned above.

**Comment by rdaci23** [comment]
cool. thanks
